name: Phoenix Docker Release

on:
  release:
    types:
      - created

jobs:
  push-to-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Test
        run: echo "Working"
